spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false


  session:
    jdbc:
      initialize-schema=always:
server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health